'use strict';
(function(root){
const types=['Operacional','Funcional','Não funcional','Normativo'];
const now=()=>new Date().toISOString();
const uid=()=>crypto.randomUUID();
function project(name,objectives,delivery){return {schemaVersion:1,id:uid(),name,objectives,delivery,createdAt:now(),updatedAt:now(),revision:0,cycle:1,closed:false,nextReq:1,eap:[],activities:[],requirements:[],matrices:[]};}
function nextId(p){return 'REQ'+String(p.nextReq++).padStart(3,'0');}
function descendants(p,id){const all=new Set([id]);let changed=true;while(changed){changed=false;for(const e of p.eap)if(all.has(e.parent)&&!all.has(e.id)){all.add(e.id);changed=true;}}return all;}
function validationErrors(p,r){const errors=[];for(const [k,label] of Object.entries({definition:'Definição',description:'Descrição',classification:'Classificação',owner:'Responsável pelo detalhamento',validator:'Responsável pela validação',verifier:'Responsável pela verificação',quantity:'Grandeza ou condição verificável',value:'Valor esperado',unit:'Unidade ou escala',test:'Critério de teste',assessment:'Avaliação de viabilidade'}))if(!String(r[k]||'').trim())errors.push(label+' é obrigatório.');if(!p.eap.some(e=>e.id===r.eapId))errors.push('Vincule um elemento da EAP.');if(!types.includes(r.classification))errors.push('Classificação inválida.');if(!r.consistent)errors.push('Certifique a consistência.');if(!r.complete)errors.push('Certifique a completude.');if(!r.measurable)errors.push('Certifique a medida e o critério de teste.');if((r.competitors||[]).length&&!r.priority)errors.push('Defina a prioridade entre requisitos concorrentes.');return errors;}
function cycleExists(p,r){const links=new Map(p.requirements.map(x=>[x.id,x.dependencies||[]]));links.set(r.id,r.dependencies||[]);const active=new Set(),done=new Set();function visit(id){if(active.has(id))return true;if(done.has(id))return false;active.add(id);for(const d of links.get(id)||[])if(visit(d))return true;active.delete(id);done.add(id);return false;}return [...links.keys()].some(visit);}
function snapshot(p){return {version:p.matrices.length+1,cycle:p.cycle,generatedAt:now(),projectName:p.name,objectives:p.objectives,delivery:p.delivery,eap:structuredClone(p.eap),activities:structuredClone(p.activities),requirements:structuredClone(p.requirements)};}
function validateImport(p){if(!p||p.schemaVersion!==1||typeof p.id!=='string'||typeof p.name!=='string'||!p.name.trim()||typeof p.objectives!=='string'||!p.objectives.trim()||typeof p.delivery!=='string'||!p.delivery.trim())throw Error('Arquivo de projeto inválido ou formato não suportado.');for(const k of ['eap','activities','requirements','matrices'])if(!Array.isArray(p[k]))throw Error('Estrutura incompleta: '+k);if(!Number.isSafeInteger(p.nextReq)||p.nextReq<1||!Number.isSafeInteger(p.cycle)||p.cycle<1||typeof p.closed!=='boolean')throw Error('Controle de ciclo inválido.');for(const list of [p.eap,p.activities,p.requirements]){const ids=new Set();for(const x of list){if(!x||typeof x.id!=='string'||ids.has(x.id))throw Error('Identificadores inválidos ou duplicados.');ids.add(x.id);}}const eid=new Set(p.eap.map(e=>e.id)),rid=new Set(p.requirements.map(r=>r.id)),aid=new Set(p.activities.map(a=>a.id));for(const e of p.eap){if(typeof e.name!=='string'||(e.parent&&!eid.has(e.parent)))throw Error('EAP inválida.');let node=e,seen=new Set();while(node){if(seen.has(node.id))throw Error('Ciclo na EAP.');seen.add(node.id);node=p.eap.find(x=>x.id===node.parent);}}for(const a of p.activities)if(!eid.has(a.eapId)||typeof a.name!=='string')throw Error('Atividade sem EAP válida.');for(const r of p.requirements){if(!/^REQ\d{3,}$/.test(r.id)||Number(r.id.slice(3))>=p.nextReq||!eid.has(r.eapId)||!types.includes(r.classification)||!['provisional','validated'].includes(r.status)||!Array.isArray(r.modifications)||!Array.isArray(r.dependencies)||!Array.isArray(r.competitors))throw Error('Requisito inválido.');if(r.dependencies.some(x=>!rid.has(x)||x===r.id)||r.competitors.some(x=>!rid.has(x)||x===r.id)||cycleExists(p,r))throw Error('Dependências inválidas.');if(r.activityId&&!aid.has(r.activityId))throw Error('Atividade de verificação inexistente.');if(r.status==='validated'&&validationErrors(p,r).length)throw Error('Requisito validado incompleto.');}for(const m of p.matrices)if(!m||!Number.isInteger(m.version)||!Array.isArray(m.requirements)||!Array.isArray(m.eap)||!Array.isArray(m.activities))throw Error('Matriz inválida.');return p;}
root.RequirementsModel={types,now,uid,project,nextId,descendants,validationErrors,cycleExists,snapshot,validateImport};
})(typeof window!=='undefined'?window:globalThis);
